// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG4QliS6HTtjYLDsA8pXBVpTjt_-vcURM',
    appId: '1:177090178888:web:f8c9560962e7bd9e94cd7d',
    messagingSenderId: '177090178888',
    projectId: 'mediscan-48800',
    authDomain: 'mediscan-48800.firebaseapp.com',
    storageBucket: 'mediscan-48800.firebasestorage.app',
    measurementId: 'G-4Q7WDD9B9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZwiDJ2Yl0GWDUMuIMfT7Aq1xu8vqSyfA',
    appId: '1:177090178888:android:080f93748283267394cd7d',
    messagingSenderId: '177090178888',
    projectId: 'mediscan-48800',
    storageBucket: 'mediscan-48800.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKImBsqsxUsuYsUOvno1lF06dC4zj1G4Q',
    appId: '1:177090178888:ios:11677e339433593694cd7d',
    messagingSenderId: '177090178888',
    projectId: 'mediscan-48800',
    storageBucket: 'mediscan-48800.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKImBsqsxUsuYsUOvno1lF06dC4zj1G4Q',
    appId: '1:177090178888:ios:11677e339433593694cd7d',
    messagingSenderId: '177090178888',
    projectId: 'mediscan-48800',
    storageBucket: 'mediscan-48800.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG4QliS6HTtjYLDsA8pXBVpTjt_-vcURM',
    appId: '1:177090178888:web:8e3041c5d5eca33694cd7d',
    messagingSenderId: '177090178888',
    projectId: 'mediscan-48800',
    authDomain: 'mediscan-48800.firebaseapp.com',
    storageBucket: 'mediscan-48800.firebasestorage.app',
    measurementId: 'G-52X96LZ72L',
  );

}